site_name: Khalti Gateway Docs

pages:
        - Welcome: index.md
        - Getting started: getting-started.md
        - Integration:
                - Web: checkout/web.md
                - Android: checkout/android.md
                - iOS: checkout/ios.md
                - Prestashop: checkout/prestashop.md
                - WooCommerce: checkout/woocommerce.md
        - Low level API:
                - Wallet : checkout/diy-wallet.md
                - Ebanking : checkout/diy-ebanking.md
        - Verification:
                - Verification: api/verification.md
                - Transaction: api/transaction.md
        - Contribution: contribution.md
theme: readthedocs
docs_dir: content
site_dir: docs
