site_name: Khalti Gateway Docs

pages:
        - Welcome: index.md
        - Getting started: getting-started.md
        - Widget:
                - Web: checkout/web.md
                - Android: checkout/android.md
                - iOS: checkout/ios.md
        - Verification:
                - Verification: api/verification.md
                - Transaction: api/transaction.md
theme: readthedocs
docs_dir: content
site_dir: docs
